// src/quaternion/ideal.rs

use crate::quaternion::algebra::{BigIntAlg, IntQuat, QuatConfig, RatQuat};
use crate::quaternion::lattice::QuatLattice;

#[derive(Clone, Debug)]
pub struct QuatLeftIdeal<T: BigIntAlg, P: QuatConfig<T>> {
    pub lattice: QuatLattice<T, P>,
    pub norm: T,
    pub parent_order: QuatLattice<T, P>,
}

impl<T: BigIntAlg, P: QuatConfig<T>> QuatLeftIdeal<T, P> {
    /// Computes and updates the norm of the ideal based on its lattice index
    /// relative to the parent order.
    pub fn update_norm(&mut self) {
        let index = QuatLattice::index(&self.lattice, &self.parent_order);
        self.norm = index.sqrt(); 
    }

    /// Verifies if the stored norm matches the computed lattice index.
    pub fn verify_norm(&self) -> u32 {
        let index = QuatLattice::index(&self.lattice, &self.parent_order);
        self.norm.ct_eq(&index.sqrt())
    }

    /// Evaluates structural and mathematical equality in constant time.
    pub fn ct_eq(&self, other: &Self) -> u32 {
        QuatLattice::equal(&self.parent_order, &other.parent_order)
            & self.norm.ct_eq(&other.norm)
            & QuatLattice::equal(&self.lattice, &other.lattice)
    }

    /// Creates a principal left ideal generated by `x` in `order`.
    /// I = order * x
    pub fn create_principal(order: &QuatLattice<T, P>, x: &RatQuat<T, P>) -> Self {
        // Multiply order on the right by x
        let mut lattice = QuatLattice::alg_elem_mul(order, x);
        lattice.reduce_denom();

        // TODO: faster way to deduce nrd?
        let (norm_num, norm_denom) = x.norm();
        debug_assert!(
            norm_denom.ct_eq(&T::one()) == u32::MAX, 
            "Principal ideal generator must have integer norm"
        );

        Self {
            lattice,
            norm: norm_num,
            parent_order: order.clone(),
        }
    }

    /// Creates a left ideal generated by an element `x` and an integer `N`.
    /// I = order * x + order * N
    pub fn create(order: &QuatLattice<T, P>, x: &RatQuat<T, P>, n: &T) -> Self {
        debug_assert!(!x.is_zero(), "Generator x cannot be zero");

        let principal = Self::create_principal(order, x);

        // Ideal generated by N: scale the basis of the order by N
        let mut order_n = order.clone();
        for i in 0..4 {
            order_n.generators[i] = &order_n.generators[i] * n;
        }
        // TODO: have integer multiplication defined for lattices instead

        let mut lattice = QuatLattice::add_lazy(&principal.lattice, &order_n);
        lattice.hnf();

        let mut ideal = Self {
            lattice,
            norm: T::zero(), // TODO: faster computation?
            parent_order: order.clone(),
        };
        ideal.update_norm();
        ideal
    }

    /// Computes the sum of two left ideals (I1 + I2).
    pub fn add(i1: &Self, i2: &Self) -> Self {
        debug_assert!(
            QuatLattice::equal(&i1.parent_order, &i2.parent_order) == u32::MAX,
            "Ideals must have the same parent order"
        );

        let mut sum_lattice = QuatLattice::add_lazy(&i1.lattice, &i2.lattice);
        sum_lattice.hnf();

        let mut sum_ideal = Self {
            lattice: sum_lattice,
            norm: T::zero(),
            parent_order: i1.parent_order.clone(),
        };
        sum_ideal.update_norm();
        sum_ideal
    }

    /// Computes the intersection of two left ideals (I1 \cap I2).
    pub fn intersect(i1: &Self, i2: &Self) -> Self {
        debug_assert!(
            QuatLattice::equal(&i1.parent_order, &i2.parent_order) == u32::MAX,
            "Ideals must have the same parent order"
        );

        let mut inter_lattice = QuatLattice::intersect(&i1.lattice, &i2.lattice);
        inter_lattice.hnf();

        let mut inter_ideal = Self {
            lattice: inter_lattice,
            norm: T::zero(),
            parent_order: i1.parent_order.clone(),
        };
        inter_ideal.update_norm();
        inter_ideal
    }

    /// Multiplies the ideal by an element alpha on the right.
    /// Product = I * alpha
    pub fn mul(ideal: &Self, alpha: &RatQuat<T, P>) -> Self {
        let mut prod_lattice = QuatLattice::alg_elem_mul(&ideal.lattice, alpha);
        prod_lattice.hnf();

        let (alpha_norm_num, alpha_norm_denom) = alpha.norm();

        let mut prod_norm = ideal.norm.clone() * alpha_norm_num;
        debug_assert!(
            (prod_norm.clone() % alpha_norm_denom.clone()).is_zero(),
            "Norm division failure during ideal multiplication"
        );
        prod_norm = prod_norm / alpha_norm_denom;

        let prod_ideal = Self {
            lattice: prod_lattice,
            norm: prod_norm,
            parent_order: ideal.parent_order.clone(),
        };

        debug_assert!(
            prod_ideal.verify_norm() == u32::MAX, 
            "Ideal norm verification failed after multiplication"
        );

        prod_ideal
    }

    /// Returns the conjugate of the ideal (not in HNF).
    pub fn conjugate_without_hnf(&self, new_parent_order: &QuatLattice<T, P>) -> Self {
        Self {
            lattice: self.lattice.conjugate_without_hnf(),
            norm: self.norm.clone(),
            parent_order: new_parent_order.clone(),
        }
    }

    /// Searches for a generator of the ideal (an element `gen` in `I` 
    /// such that gcd(nrd(gen)/nrd(I), nrd(I)) == 1).
    pub fn generator(&self) -> Option<RatQuat<T, P>> {
        let mut int_norm = 1_i32;

        // Exhaustive search expanding by L1 norm
        loop {
            // Cutoff to prevent infinite loops in malformed ideals
            if int_norm > 150 { return None; }

            for a in -int_norm..=int_norm {
                for b in (-int_norm + a.abs())..=(int_norm - a.abs()) {
                    for c in (-int_norm + a.abs() + b.abs())..=(int_norm - a.abs() - b.abs()) {
                        let d = int_norm - a.abs() - b.abs() - c.abs();

                        let a_t = T::from_i32(a);
                        let b_t = T::from_i32(b);
                        let c_t = T::from_i32(c);
                        let d_t = T::from_i32(d);

                        // Check if gcd(a, b, c, d) == 1
                        let gcd_val = a_t.gcd(&b_t).gcd(&c_t).gcd(&d_t);
                        // TODO: precompute a,b,c,d up to here
                        if gcd_val.ct_eq(&T::one()) == u32::MAX {

                            // Evaluate basis vector: gen = lattice.basis * (a, b, c, d)
                            let mut coords = [T::zero(), T::zero(), T::zero(), T::zero()];
                            let scalars = [&a_t, &b_t, &c_t, &d_t];

                            for i in 0..4 {
                                let mut sum = T::zero();
                                for j in 0..4 {
                                    sum = sum + self.lattice.generators[j].coords[i].clone() * scalars[j].clone();
                                }
                                coords[i] = sum;
                            }

                            let gen_int = IntQuat::new(coords[0].clone(), coords[1].clone(), coords[2].clone(), coords[3].clone());
                            let gen_rat = RatQuat::new(gen_int, self.lattice.denom.clone());

                            let (norm_n, norm_d) = gen_rat.norm();
                            if norm_d.ct_eq(&T::one()) == u32::MAX {
                                let q = norm_n.clone() / self.norm.clone();
                                let r = norm_n.clone() % self.norm.clone();

                                if r.is_zero() && self.norm.gcd(&q).ct_eq(&T::one()) == u32::MAX {
                                    return Some(gen_rat);
                                }
                            }
                        }
                    }
                }
            }
            int_norm += 1;
        }
    }
}

// ========================================================================
// Order Operations
// ========================================================================

/// Computes the discriminant of an order.
pub fn quat_order_discriminant<T: BigIntAlg, P: QuatConfig<T>>(order: &QuatLattice<T, P>) -> T {
    let p = P::p();

    // The reduced trace form matrix for the standard basis (1, i, j, k) is diag(2, 2, 2p, 2p).
    let gram = [
        [T::from_i32(2), T::zero(), T::zero(), T::zero()],
        [T::zero(), T::from_i32(2), T::zero(), T::zero()],
        [T::zero(), T::zero(), T::from_i32(2) * p.clone(), T::zero()],
        [T::zero(), T::zero(), T::zero(), T::from_i32(2) * p.clone()],
    ];

    // det(basis^T * gram * basis)
    let mut prod = [
        [T::zero(), T::zero(), T::zero(), T::zero()],
        [T::zero(), T::zero(), T::zero(), T::zero()],
        [T::zero(), T::zero(), T::zero(), T::zero()],
        [T::zero(), T::zero(), T::zero(), T::zero()],
    ];

    for i in 0..4 {
        for j in 0..4 {
            let mut sum = T::zero();
            for k in 0..4 {
                sum = sum + order.generators[i].coords[k].clone() * gram[k][j].clone();
            }
            prod[i][j] = sum;
        }
    }

    let mut final_prod = [
        [T::zero(), T::zero(), T::zero(), T::zero()],
        [T::zero(), T::zero(), T::zero(), T::zero()],
        [T::zero(), T::zero(), T::zero(), T::zero()],
        [T::zero(), T::zero(), T::zero(), T::zero()],
    ];

    for i in 0..4 {
        for j in 0..4 {
            let mut sum = T::zero();
            for k in 0..4 {
                sum = sum + prod[i][k].clone() * order.generators[j].coords[k].clone();
            }
            final_prod[i][j] = sum;
        }
    }

    let mut final_mat: [IntQuat<T, P>; 4] = [
        IntQuat::zero(),
        IntQuat::zero(),
        IntQuat::zero(),
        IntQuat::zero()
    ];
    for i in 0..4 {
        final_mat[i] = IntQuat::new(
            final_prod[i][0].clone(), final_prod[i][1].clone(), 
            final_prod[i][2].clone(), final_prod[i][3].clone()
        );
    }

    let det = crate::quaternion::matrix::MatrixUtils::mat_4x4_inv_with_det_as_denom(None, &final_mat);

    let denom_sq = order.denom.clone() * order.denom.clone();
    let denom_4 = denom_sq.clone() * denom_sq;
    let denom_8 = denom_4.clone() * denom_4.clone();

    let sqr = det / denom_8;
    sqr.sqrt()
}

/// Checks if an order is maximal (discriminant == p).
pub fn quat_order_is_maximal<T: BigIntAlg, P: QuatConfig<T>>(order: &QuatLattice<T, P>) -> u32 {
    let disc = quat_order_discriminant(order);
    disc.ct_eq(P::p())
}
